### ISSUE TITLE
Service 和IService

### ISSUE THREAD

**Issue by henryssss** [m24927605/Nest-Virtual-Currency#1]
控制器Controller层,直接调用Service,为什么不是调用service的接口方法!
那么,Service的接口 起了什么作用呢?没理解

**Comment by m24927605** [comment]
您提到的接口應該是Interface吧?Interface是定義好Service裏頭的方法規範，等於開了一個Service規格，定義好之後再具體去實現，Controller最後再去調用Service裏頭經過具體實現的方法。

**Comment by henryssss** [comment]
那可不可以就直接调用Service的接口方法,然后接口方法再去调用具体实现的Service呢?

**Comment by henryssss** [comment]
有没有做nestjs的Graphql部分的详解？期待。。。

**Comment by m24927605** [comment]
@henryssss 您好:
1.interface僅能定義好方法、屬性、return型別，不能直接實作。
2.您說的 "接口方法再去调用具体实现的Service
 "應該是在講interface內實作service的方法?如是，您無法在接口定義好的方法裏頭實作內容的，所以後面這句無法實現。
3.interface的用意是宣告好有什麼行為，並在寫程式過程中享受typescript intellisense 帶來的好處，class
再implement interface，實作方法細節內容。

Graphql 我還沒碰過，但會點開這技能補上nestjs相關程式碼的~只是要等等~最近很忙~
